In [1]:
print("Hello")

Hello


In [2]:
import torch

In [4]:
setence = "Hello python"
print(torch.arange(0, 2 , dtype=torch.float), torch.arange(0, 2 , dtype=torch.float).shape)
print("\n With Unsqeeze: to add batch parameter")
print(torch.arange(0, 2 , dtype=torch.float).unsqueeze(1), "\n", torch.arange(0, 2 , dtype=torch.float).unsqueeze(1).shape)


tensor([0., 1.]) torch.Size([2])

 With Unsqeeze: to add batch parameter
tensor([[0.],
        [1.]]) 
 torch.Size([2, 1])


In [5]:
print(torch.arange(0, 2 , dtype=torch.float).unsqueeze(0), "\n", torch.arange(0, 2 , dtype=torch.float).unsqueeze(0).shape)

tensor([[0., 1.]]) 
 torch.Size([1, 2])


In [7]:
pe= torch.zeros(10, 4)
pe

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
pe[:, 0::2]= 1

In [9]:
pe

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 0.]])

In [ ]:
pe[:,0::2] # even cols

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [14]:
pe, pe.shape

(tensor([[1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.]]),
 torch.Size([10, 4]))

In [ ]:
pe_sq= pe.unsqueeze(0)
pe_sq, pe_sq.shape #(1, seqlen, d_model)

(tensor([[[1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.]]]),
 torch.Size([1, 10, 4]))

In [19]:
pe_sq= pe.unsqueeze(0)
pe_sq, pe_sq.shape

(tensor([[[1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.],
          [1., 0., 1., 0.]]]),
 torch.Size([1, 10, 4]))

In [21]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
mask=0
torch.ones(4,4).masked_fill_(mask==0,-1e9 )

TypeError: masked_fill_() received an invalid combination of arguments - got (bool, float), but expected one of:
 * (Tensor mask, Tensor value)
      didn't match because some of the arguments have invalid types: (!bool!, !float!)
 * (Tensor mask, Number value)
      didn't match because some of the arguments have invalid types: (!bool!, !float!)


# Transpose Analysis

In [28]:
a= torch.rand(2,4,6)
a, a.shape

(tensor([[[0.6236, 0.8908, 0.6641, 0.4607, 0.4849, 0.5822],
          [0.3701, 0.7083, 0.2722, 0.4122, 0.9365, 0.2049],
          [0.7332, 0.0534, 0.6546, 0.6742, 0.2707, 0.6282],
          [0.9088, 0.1076, 0.6441, 0.1696, 0.8745, 0.8239]],
 
         [[0.3982, 0.1888, 0.8399, 0.5981, 0.7904, 0.0173],
          [0.0893, 0.4985, 0.3218, 0.6895, 0.2515, 0.3900],
          [0.3617, 0.4890, 0.6890, 0.3687, 0.9611, 0.6168],
          [0.7797, 0.5307, 0.5546, 0.9671, 0.3759, 0.8230]]]),
 torch.Size([2, 4, 6]))

In [31]:
a_t= a.transpose(1,2)
a_t, a_t.shape
# If a has a shape of [batch_size, seq_length, feature_dim], then:

# a.shape = [batch_size, seq_length, feature_dim]
# After a.transpose(1, 2), the shape will be [batch_size, feature_dim, seq_length].
# The first dimension (batch size) is unaffected, while the second and third dimensions are swapped.

(tensor([[[0.6236, 0.3701, 0.7332, 0.9088],
          [0.8908, 0.7083, 0.0534, 0.1076],
          [0.6641, 0.2722, 0.6546, 0.6441],
          [0.4607, 0.4122, 0.6742, 0.1696],
          [0.4849, 0.9365, 0.2707, 0.8745],
          [0.5822, 0.2049, 0.6282, 0.8239]],
 
         [[0.3982, 0.0893, 0.3617, 0.7797],
          [0.1888, 0.4985, 0.4890, 0.5307],
          [0.8399, 0.3218, 0.6890, 0.5546],
          [0.5981, 0.6895, 0.3687, 0.9671],
          [0.7904, 0.2515, 0.9611, 0.3759],
          [0.0173, 0.3900, 0.6168, 0.8230]]]),
 torch.Size([2, 6, 4]))

In [38]:
# Another Example 
c= torch.rand(1,2,5,6)
c, c.shape


(tensor([[[[0.2564, 0.4623, 0.4832, 0.3531, 0.0852, 0.1299],
           [0.0043, 0.2585, 0.7186, 0.4281, 0.9582, 0.3894],
           [0.8554, 0.8641, 0.1721, 0.8862, 0.4902, 0.1209],
           [0.4561, 0.8694, 0.0347, 0.5804, 0.5318, 0.6702],
           [0.2690, 0.5318, 0.9827, 0.5646, 0.1534, 0.5824]],
 
          [[0.2476, 0.2175, 0.7794, 0.0643, 0.1384, 0.9333],
           [0.0560, 0.3049, 0.7617, 0.5688, 0.9780, 0.5354],
           [0.2187, 0.3732, 0.5589, 0.2344, 0.5834, 0.6484],
           [0.5494, 0.6662, 0.1948, 0.5354, 0.4381, 0.5817],
           [0.3530, 0.5687, 0.3512, 0.2544, 0.3966, 0.8198]]]]),
 torch.Size([1, 2, 5, 6]))

In [51]:
d = c.transpose(1,2)
c.shape, d.shape

(torch.Size([1, 2, 5, 6]), torch.Size([1, 5, 2, 6]))

In [52]:
d = c.transpose(-1,2)
c.shape, d.shape

(torch.Size([1, 2, 5, 6]), torch.Size([1, 2, 6, 5]))