In [1]:
print("Hello")

Hello


In [2]:
import torch
import torch.nn as nn

In [4]:
## NN.Embedding
vocab_size = 2 
embed_dims= 4
nn.Embedding(vocab_size, embedding_dim=embed_dims)

Embedding(2, 4)

## nn.Embeddings

In [27]:
# an Embedding module containing 23 tensors (from Zero to 22) of size 4
embedding = nn.Embedding(num_embeddings= 23, embedding_dim= 4)
# a batch of 2 samples of 4 indices each
input = torch.LongTensor([[1, 2, 4, 5, 6,7,8,9,22], [4, 3, 2, 9,5,7,8,9,22]])
print(embedding(input))
# 1,2,4,5,3,9,6, 7, 8,9,
# 8 +1
## here (Input Value/tensor element should be less than 23, as we passed num_embedding=23)
## It'll accept number till 22 only, else throw Error

## Embedding Dimensions
# As here Embedding Dimension set as 4: 
# So Each number will be represented by 4 dims

tensor([[[-0.0280, -0.1462, -0.1974, -0.7201],
         [ 0.9385, -0.0535,  0.1047, -1.4124],
         [-0.8077, -1.3785, -1.2666,  1.0047],
         [-0.3406,  0.5757,  0.5708, -1.1245],
         [ 0.3573, -2.5372,  0.6559, -0.5169],
         [ 0.3628,  0.4259,  1.2958,  0.5087],
         [-0.2399,  1.4832, -0.8201, -0.0881],
         [ 0.7397, -0.7980, -0.2014,  1.3863],
         [ 0.1658,  0.4730,  0.7593, -0.8754]],

        [[-0.8077, -1.3785, -1.2666,  1.0047],
         [-2.4329, -1.0504,  0.7781, -0.9709],
         [ 0.9385, -0.0535,  0.1047, -1.4124],
         [ 0.7397, -0.7980, -0.2014,  1.3863],
         [-0.3406,  0.5757,  0.5708, -1.1245],
         [ 0.3628,  0.4259,  1.2958,  0.5087],
         [-0.2399,  1.4832, -0.8201, -0.0881],
         [ 0.7397, -0.7980, -0.2014,  1.3863],
         [ 0.1658,  0.4730,  0.7593, -0.8754]]], grad_fn=<EmbeddingBackward0>)


In [ ]:
print(embedding(input).shape)
# torch.Size([2, 9, 4])
# Batch Size, rows, cols 
# or Batch Size, no_elements, EmbedDims

torch.Size([2, 9, 4])


In [ ]:
# example with padding_idx
#  specified, the entries at padding_idx do not contribute to the gradient; therefore, the embedding vector at padding_idx is not updated during training, i.e. it remains as a fixed “pad”. For a newly constructed Embedding, the embedding vector at padding_idx will default to all zeros, but can be updated to another value to be used as the padding vector.
embedding = nn.Embedding(10, 3, padding_idx=0)
input = torch.LongTensor([[1, 2, 1, 5]])
embedding(input)

tensor([[[-0.2311, -0.1467,  1.6282],
         [ 0.4952, -0.2592,  0.2595],
         [-0.2311, -0.1467,  1.6282],
         [ 0.1102, -0.2073,  0.9205]]], grad_fn=<EmbeddingBackward0>)

In [41]:
tens = torch.LongTensor([[1, 2, 4, 5, 6,7,8,9,22,24], 
                  [4, 3, 2, 9,5,7,8,9,22,28]])
tens.shape

torch.Size([2, 10])

In [42]:
batch_size, seq_length =tens.shape
batch_size, seq_length

(2, 10)

## torch.arange()

In [44]:
torch.arange(256)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [53]:
pos_embedding= nn.Embedding(256, 4)
seq_length= 10
positional_embedding= pos_embedding(torch.arange(10))
print("Tokens position: ",torch.arange(10))
print("positional Embeddings Shape>> ", positional_embedding.shape)
print("positional Embeddings >> ", positional_embedding)

Tokens position:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
positional Embeddings Shape>>  torch.Size([10, 4])
positional Embeddings >>  tensor([[-1.9608, -1.4489, -1.1177,  1.2926],
        [-0.9589, -0.9396,  1.9117, -1.1692],
        [-0.0338, -0.8293,  0.9690, -0.1280],
        [ 1.0294, -0.4790,  0.9730, -1.5220],
        [-1.9138, -0.1396, -0.1988,  0.6087],
        [-0.2801,  0.7829, -1.2065,  1.1446],
        [-0.2788,  0.1322,  0.8448,  0.6094],
        [-0.3390, -0.5185, -1.0499,  0.5883],
        [ 0.4952,  0.3570, -0.2264,  0.0921],
        [ 1.1720,  0.4919, -1.1811, -0.2674]], grad_fn=<EmbeddingBackward0>)


In [54]:
tok_emb= nn.Embedding(256, 4)
seq_length= 10
token_embedding= tok_emb(torch.arange(10))
print("Embedding Tokens : ",torch.arange(10))
print("token Embeddings Shape>> ", token_embedding.shape)
print("Token Embeddings >> ", token_embedding)

Embedding Tokens :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
token Embeddings Shape>>  torch.Size([10, 4])
Token Embeddings >>  tensor([[ 1.1816e+00,  4.7038e-01, -5.1939e-02,  1.1171e+00],
        [ 7.6613e-01,  2.2593e-01,  2.8409e-01,  1.6862e+00],
        [-5.6263e-01, -2.4929e-01,  1.2803e-01,  1.7724e+00],
        [-1.5313e+00, -3.1009e-01, -2.2577e+00,  1.6232e+00],
        [-6.2501e-02,  4.3446e-01,  1.0153e+00,  1.4387e+00],
        [ 8.0280e-01, -3.3533e-01,  9.9792e-01, -5.6364e-01],
        [ 5.6120e-01, -3.8867e-01, -8.0653e-01,  1.5267e-01],
        [-6.7787e-01, -1.7172e+00,  1.5969e-03,  2.8122e-01],
        [ 1.5161e+00, -2.1682e-01,  3.7225e-01, -7.7389e-01],
        [ 1.3797e-01,  1.4421e+00,  1.6830e+00,  1.1525e-01]],
       grad_fn=<EmbeddingBackward0>)


In [60]:
token_embedding + positional_embedding

tensor([[-0.7792, -0.9785, -1.1697,  2.4096],
        [-0.1928, -0.7137,  2.1958,  0.5171],
        [-0.5964, -1.0786,  1.0971,  1.6444],
        [-0.5019, -0.7891, -1.2847,  0.1012],
        [-1.9763,  0.2949,  0.8165,  2.0474],
        [ 0.5227,  0.4476, -0.2085,  0.5810],
        [ 0.2824, -0.2565,  0.0383,  0.7621],
        [-1.0169, -2.2357, -1.0483,  0.8695],
        [ 2.0113,  0.1402,  0.1459, -0.6818],
        [ 1.3099,  1.9340,  0.5018, -0.1522]], grad_fn=<AddBackward0>)

## NN.linear()

```markdown
# `torch.nn.Linear` in PyTorch

In PyTorch, `torch.nn.Linear` is a commonly used layer that applies a **linear transformation** (also known as a **fully connected** or **dense** layer) to the input data. It is part of the `torch.nn` module, which contains various neural network layers.

## Definition
```python
torch.nn.Linear(in_features, out_features, bias=True)
```

### Parameters
- **`in_features`**: The size of each input sample (number of input features).
- **`out_features`**: The size of each output sample (number of output features).
- **`bias`** (optional): If `True`, includes a learnable bias term. By default, it is set to `True`.

## Mathematical Operation
For an input vector \( x \) and weight matrix \( W \) with an optional bias \( b \), the output \( y \) of the linear layer is computed as:

\[
y = xW^T + b
\]

### Notation
- **\( x \)**: Input tensor of shape \((N, \text{in\_features})\)
- **\( W \)**: Weight tensor of shape \((\text{out\_features}, \text{in\_features})\)
- **\( b \)**: Bias tensor of shape \((\text{out\_features})\)

This linear transformation layer is a fundamental building block for creating fully connected layers in neural network architectures.
```

In [73]:
d_model = 2
qkv = nn.Linear(d_model, d_model*3, bias=False)

In [76]:
m = nn.Linear(20, 30)
input = torch.randn(128, 20)
output = m(input)
print(output.size())

torch.Size([128, 30])


In [79]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a simple neural network with one hidden layer
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.hidden = nn.Linear(4, 3)  # 4 input features, 3 hidden units
        self.output = nn.Linear(3, 4)  # 3 hidden units, 1 output

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        x = self.output(x)
        return x

# Instantiate the model
model = SimpleNN()

# Define a sample input
input_data = torch.tensor([[0.5, 0.3, 0.2, 0.1]])

# Perform a forward pass
output_data = model(input_data)

print("Output:", output_data)


Output: tensor([[ 0.4407, -0.0099,  0.0658, -0.2887]], grad_fn=<AddmmBackward0>)


In [80]:
# Define a sample input
input_data = torch.tensor([[0.5, 0.3, 0.2, 0.1], 
                           [0.5, 0.3, 0.2, 0.1],
                           [0.5, 0.3, 0.2, 0.1],
                           [0.5, 0.3, 0.2, 0.1]])

# Perform a forward pass
output_data = model(input_data)

print("Output:", output_data)

Output: tensor([[ 0.4407, -0.0099,  0.0658, -0.2887],
        [ 0.4407, -0.0099,  0.0658, -0.2887],
        [ 0.4407, -0.0099,  0.0658, -0.2887],
        [ 0.4407, -0.0099,  0.0658, -0.2887]], grad_fn=<AddmmBackward0>)


# QKV in transformer


# Shapes of \( Q \), \( K \), and \( V \) in Transformer Architecture

In Transformer architectures, the shapes of the **Query (Q)**, **Key (K)**, and **Value (V)** tensors are determined by the following factors:

1. **Input Embedding Dimension** (`embed_dim`): The size of the input embeddings, denoted as \( d_{\text{model}} \).
2. **Number of Attention Heads** (`num_heads`): The number of parallel attention heads, denoted as \( h \).
3. **Head Dimension** (`head_dim`): The size of each attention head, calculated as:

   \[
   \text{head\_dim} = \frac{\text{embed\_dim}}{\text{num\_heads}}
   \]

## Shapes of \( Q \), \( K \), and \( V \)

Given an input tensor with shape:

\[
(\text{batch\_size}, \text{seq\_length}, \text{embed\_dim})
\]

The shapes of the Query (Q), Key (K), and Value (V) tensors after applying linear transformations are:

\[
Q, K, V: \; (\text{batch\_size}, \text{seq\_length}, \text{embed\_dim})
\]

### After Reshaping and Splitting into Heads

For multi-head attention, we reshape \( Q \), \( K \), and \( V \) to include the number of heads:

\[
(\text{batch\_size}, \text{num\_heads}, \text{seq\_length}, \text{head\_dim})
\]

where:

\[
\text{head\_dim} = \frac{\text{embed\_dim}}{\text{num\_heads}}
\]

### Concatenated Output Shape

After computing attention scores, the outputs from all heads are concatenated along the embedding dimension:

\[
\text{Output Shape}: \; (\text{batch\_size}, \text{seq\_length}, \text{embed\_dim})
\]

## Example Calculation

Suppose:

- \( \text{embed\_dim} = 512 \)
- \( \text{num\_heads} = 8 \)

Then:

1. **Head Dimension**:

   \[
   \text{head\_dim} = \frac{512}{8} = 64
   \]

2. **Shape of \( Q \), \( K \), and \( V \) After Reshaping**:

   \[
   (\text{batch\_size}, 8, \text{seq\_length}, 64)
   \]

3. **Concatenated Output Shape**:

   \[
   (\text{batch\_size}, \text{seq\_length}, 512)
   \]

## Summary

- **Initial Shape** of \( Q \), \( K \), and \( V \): \( (\text{batch\_size}, \text{seq\_length}, \text{embed\_dim}) \)
- **After Splitting into Heads**: \( (\text{batch\_size}, \text{num\_heads}, \text{seq\_length}, \text{head\_dim}) \)
- **Final Concatenated Shape**: \( (\text{batch\_size}, \text{seq\_length}, \text{embed\_dim}) \)

This process ensures the attention mechanism can focus on different parts of the input sequence in parallel while maintaining the input-output dimensional consistency.


# **```torch.view() : Shares the memory with original tensor```**

In [83]:
a = torch.rand(4,3)
a, a.shape

(tensor([[0.5675, 0.4145, 0.7603],
         [0.5765, 0.1945, 0.4622],
         [0.5675, 0.8992, 0.1230],
         [0.6485, 0.3061, 0.1271]]),
 torch.Size([4, 3]))

In [84]:
import torch

# Original tensor of shape (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original shape:", tensor.shape)

# Reshape to (3, 2)
reshaped_tensor = tensor.view(3, 2)
print("Reshaped shape:", reshaped_tensor.shape)
print(reshaped_tensor)


Original shape: torch.Size([2, 3])
Reshaped shape: torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


-1: When you use -1 as a dimension in the .view() method, it tells PyTorch to infer this dimension based on the size of the original tensor. This is useful when you don't know or don't want to specify the exact size of one dimension but want to ensure the total number of elements remains the same.

2: This specifies that the new shape should have 2 elements in this dimension

In [95]:
# Original tensor of shape (2, 3)
x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]])
print( "Original matrix :" , a, "\n")

# Reshape using -1
z = x.view(-1, 2)
print("Inferred shape:", z.shape, "\n")
print("Viewed output: ", z)


Original matrix : tensor([[1, 2, 3],
        [4, 5, 6]]) 

Inferred shape: torch.Size([3, 2]) 

Viewed output:  tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [96]:
# chaning z changes x (Because View of the tensor shares the same memory as the original input)
z[ :, 0] = 88
z,x

(tensor([[88,  2],
         [88,  4],
         [88,  6]]),
 tensor([[88,  2, 88],
         [ 4, 88,  6]]))

In [89]:
tensor.view(-1, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [97]:
import torch.nn.functional as F

In [100]:
F.scaled_dot_product_attention()

AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'

In [107]:
import torch
print(torch.__version__)

1.10.2
